name: mobile-config-firefox
buildsystem: simple
sources:
  - type: git
    url: https://gitlab.postmarketos.org/postmarketOS/mobile-config-firefox
    commit: 6b0da1050a04e88d0e0c5bc8bd324ae5550de44b
    x-checker-data:
      type: git
    tag: 5.1.0
  - type: patch
    paths:
      - patches/autoconfig.patch # loading gnome theme, replace /etc with /app/etc
      - patches/browsercss.patch # remove close app button and firefox logo
      - patches/home.patch # remove firefox logo from newtab
build-commands:
  # get all firefox search engines back
  # disable annoying check for default browser
  - jq 'del(.policies.SearchEngines)|.policies.DontCheckDefaultBrowser=true' src/policies.json
    | tee src/policies.tmp
  - mv src/policies.tmp src/policies.json
  - make install DESTDIR=/app FIREFOX_DIR=lib/firefox FIREFOX_CONFIG_DIR=lib/firefox/distribution
  - mkdir /app/etc/firefox
  # these files should be moved, otherwise they not work
  - mv /app/lib/firefox/mobile-config-autoconfig.js /app/etc/firefox/mobile-config-autoconfig.js
  - mv /app/lib/firefox/distribution/policies/policies.json /app/lib/firefox/distribution/policies.json

